baseURL = "https://example.org/"
languageCode = "en-us"
title = "Taylor's Portfolio"
theme = "Basic"

[params]
  author = "Taylor Jones"
  description = "My portfolio site"

  gh_url = "https://api.github.com/users"
  gh_user = "twjones3"